# For a CA-issued certificate, set SSLHonorCipherOrder on to enforce the server's preferred cipher order.
SSLHonorCipherOrder     On

# When using a real CA, enable SSLUseStapling and ensure the CA supports OCSP.
SSLUseStapling          On
SSLStaplingCache "shmcb:logs/ssl_stapling(32768)"