services:
  # Note: PostgreSQL is an external service. You can find more information about the configuration here:
  # https://hub.docker.com/_/postgres
  db:
    # Note: Check the recommend version here: https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#server
    image: postgres:alpine
    container_name: db
    restart: always
    volumes:
      - db:/var/lib/postgresql/data:Z
    env_file:
      - db.env

  # Note: Redis is an external service. You can find more information about the configuration here:
  # https://hub.docker.com/_/redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  app:
    image: nextcloud:apache
    container_name: app
    # hostname: app
    restart: always
    # ports:
    #   - 8080:80
    volumes:
      - nextcloud:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
      - ./nextcloud/appHooks/post-installation:/docker-entrypoint-hooks.d/post-installation
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.local app"
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: learning
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - default
      - proxy-tier

  proxy:
    build: ./proxy
    restart: always
    # container-name: proxy
    hostname: proxy
    depends_on:
      - app
      - omgwtfssl
      - omgwtfssl2
    ports:
      # - 80:80
      - 443:443
    volumes:
      - certs:/usr/local/apache2/conf/certs:ro,z
    networks:
      - proxy-tier

  # cron:
  #   image: nextcloud:apache
  #   restart: always
  #   volumes:
  #     - nextcloud:/var/www/html:z
  #     # NOTE: The `volumes` config of the `cron` and `app` containers must match
  #   entrypoint: /cron.sh
  #   depends_on:
  #     - db
  #     - redis

  # https://cloud.thesysadminhub.com/s/FNKyP43y35HGDTJ?dir=/
  # https://docs.nextcloud.com/server/28/admin_manual/office/example-docker.html#install-the-collabora-online-server
  collabora:
    image: collabora/code:latest
    hostname: collabora.local
    container_name: collabora.local
    restart: unless-stopped
    environment:
      - domain=collabora.local
      - username=admin
      - password=collaborapwd
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    cap_add:
      - MKNOD
    ports:
      - 9980:9980

  # self signed, outdated
  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=nextcloud.local
      - CA_SUBJECT=nextcloud@example.com
      - SSL_KEY=/certs/nextcloud.local.key
      - SSL_CSR=/certs/nextcloud.local.csr
      - SSL_CERT=/certs/nextcloud.local.crt
    networks:
      - proxy-tier

  # self signed, outdated
  omgwtfssl2:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=collabora.local
      - CA_SUBJECT=collabora@example.com
      - SSL_KEY=/certs/collabora.local.key
      - SSL_CSR=/certs/collabora.local.csr
      - SSL_CERT=/certs/collabora.local.crt
    networks:
      - proxy-tier

volumes:
  db:
  nextcloud:
  certs:


networks:
  proxy-tier:
