services:
  # Note: PostgreSQL is an external service. You can find more information about the configuration here:
  # https://hub.docker.com/_/postgres
  db:
    # Note: Check the recommend version here: https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#server
    image: postgres:alpine
    container_name: db
    restart: always
    volumes:
      - db:/var/lib/postgresql/data:Z
    env_file:
      - db.env

  # Note: Redis is an external service. You can find more information about the configuration here:
  # https://hub.docker.com/_/redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: always

  app:
    image: nextcloud:apache
    container_name: app
    # hostname: app
    restart: always
    # ports:
    #   - 8080:80
    volumes:
      - nextcloud:/var/www/html:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
      - ./nextcloud/appHooks/post-installation:/docker-entrypoint-hooks.d/post-installation
    # - ./nextcloud/appHooks/before-starting:/docker-entrypoint-hooks.d/before-starting
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.local app 127.0.0.1"
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: learning
    extra_hosts:
      "collabora.local": 172.19.0.4
      "nextcloud.local": 172.19.0.4
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - default
      - proxy-tier

  proxy:
    build: ./proxy
    restart: always
    # container-name: proxy
    hostname: proxy
    depends_on:
      - app
      - omgwtfssl
      - omgwtfssl2
    ports:
      # - 80:80
      - 443:443
    volumes:
      - certs:/usr/local/apache2/conf/certs:ro,z
    networks:
      - proxy-tier

  # cron:
  #   image: nextcloud:apache
  #   restart: always
  #   volumes:
  #     - nextcloud:/var/www/html:z
  #     # NOTE: The `volumes` config of the `cron` and `app` containers must match
  #   entrypoint: /cron.sh
  #   depends_on:
  #     - db
  #     - redis

  # https://cloud.thesysadminhub.com/s/FNKyP43y35HGDTJ?dir=/
  # https://docs.nextcloud.com/server/28/admin_manual/office/example-docker.html#install-the-collabora-online-server
  collabora:
    image: collabora/code:latest
    hostname: collabora
    container_name: collabora
    restart: unless-stopped
    environment:
      domain: collabora.local
      dictionaries: en
      username: admin
      password: collaborapwd
      aliasgroup1: https://nextcloud.local:443
      extra_params: "--o:ssl.enable=false --o:ssl.termination=true"
    extra_hosts:
      "collabora.local": 172.19.0.4
      "nextcloud.local": 172.19.0.4
    cap_add:
      - MKNOD
    ports:
      - 127.0.0.1:9980:9980
    networks:
      - default
      - proxy-tier
  
  coturn:
    image: instrumentisto/coturn
    hostname: coturn
    container_name: coturn
    restart: unless-stopped
    extra_hosts:
      "collabora.local": 172.19.0.4
      "nextcloud.local": 172.19.0.4
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
    networks:
      - default
    command:
      - -n
      - --log-file=stdout
      - --min-port=49160
      - --max-port=49200
      - --realm=nextcloud.local
      - --use-auth-secret
      - --static-auth-secret=passwd

  # self signed, outdated
  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=nextcloud.local
      - CA_SUBJECT=nextcloud@example.com
      - SSL_KEY=/certs/nextcloud.local.key
      - SSL_CSR=/certs/nextcloud.local.csr
      - SSL_CERT=/certs/nextcloud.local.crt
    networks:
      - proxy-tier

  # self signed, outdated
  omgwtfssl2:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=collabora.local
      - CA_SUBJECT=collabora@example.com
      - SSL_KEY=/certs/collabora.local.key
      - SSL_CSR=/certs/collabora.local.csr
      - SSL_CERT=/certs/collabora.local.crt
    networks:
      - proxy-tier

volumes:
  db:
  nextcloud:
  certs:


networks:
  proxy-tier:
