FROM nextcloud:apache

# comment out exec "$@" in entrypoint.sh using sed
# RUN sed -i 's/^[[:space:]]*exec "@"/# &/' /entrypoint.sh
# COPY ./start.sh /
# RUN chmod +x /start.sh
# ENTRYPOINT [ "/start.sh" ]