# nextcloud reverse proxy apache configuration
Listen 443

#   SSL Cipher Suite:
SSLCipherSuite ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
SSLProxyCipherSuite HIGH:MEDIUM:!MD5:!RC4:!3DES

#   SSL Protocol support:
SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
SSLHonorCipherOrder     off
SSLSessionTickets       off

# enable ssl stapling if you are using a valid certificate from a trusted CA and have OCSP support enabled on the CA side
SSLUseStapling          Off
# SSLStaplingCache "shmcb:logs/ssl_stapling(32768)"

#   Pass Phrase Dialog:
SSLPassPhraseDialog  builtin

#   Inter-Process Session Cache:
#SSLSessionCache         "dbm:${SRVROOT}/logs/ssl_scache"
SSLSessionCache        "shmcb:logs/ssl_scache(512000)"
SSLSessionCacheTimeout  300

# Prevent timeout limits on heavy processing paths like /login
ProxyTimeout 300
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5

<VirtualHost _default_:443>
    ServerName ${NEXTCLOUD_FQDN}
    # ServerAdmin admin@example.com

    # Logging
    ErrorLog "logs/nextcloud-error.log"
    CustomLog "logs/nextcloud-access.log" combined
    
    # SSL Configuration
    SSLEngine on
    SSLCertificateFile "conf/certs/${NEXTCLOUD_FQDN}.crt"
    SSLCertificateKeyFile "conf/certs/${NEXTCLOUD_FQDN}.key"

    # Security Headers
    Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
    Header always set X-Content-Type-Options "nosniff"

    # Nextcloud Discovery Redirects

    # <IfModule mod_rewrite.c>
    #     RewriteEngine on
    #     RewriteRule ^/.well-known/carddav https://%{SERVER_NAME}/remote.php/dav [R=301,L]
    #     RewriteRule ^/.well-known/caldav https://%{SERVER_NAME}/remote.php/dav [R=301,L]
    # </IfModule>
    
    Redirect 301 /.well-known/carddav /remote.php/dav
    Redirect 301 /.well-known/caldav /remote.php/dav
    Redirect 301 /.well-known/webfinger /index.php/.well-known/webfinger
    Redirect 301 /.well-known/nodeinfo /index.php/.well-known/nodeinfo

    # Proxy Core Settings
    ProxyRequests Off
    ProxyPreserveHost On
    ProxyAddHeaders On

    # Real IP Forwarding Headers
    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port "443"

     # WebSocket Support Mapping (Required for Real-time Push and Nextcloud Talk)
    ProxyPassMatch ^/(.*)/ws$ ws://app/$1/ws

    # Main Reverse Proxy Pass
    # ProxyPassReverse intercepts and rewrites the "Location" header during redirects
    ProxyPass / http://app/
    ProxyPassReverse / http://app/

    # SSLProxyEngine On
    # SSLProxyCheckPeerCN on
    # SSLProxyCheckPeerExpire on

    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
</VirtualHost>

# see the logs in container at /usr/local/apache2/logs/ folder
